url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
timeout = 12
browser = edge
environment = local
valid.username=Admin
valid.password=admin123
empty.password=
invalid.username=testing
invalid.password=test123
empty.username=
